---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
collapse = TRUE,
comment = "#>",
fig.path = "man/figures/README-",
out.width = "100%"
)
```

# roblog

Are you preparing a blog post or tech note for rOpenSci, after getting the go-ahead and a tentative publication date from our community manager [Stefanie Butland](https://ropensci.org/authors/stefanie-butland/)? Stay here! The goal of roblog is to provide guidance (docs!) and practical helpers (templates! checklists! functions!) for authors of blog posts and tech notes on rOpenSci website. 

We're looking forward to reading your content!

## Start here

In a nutshell, the process will be

* You express interest in writing for rOpenSci website. Yay!
* Our community manager [Stefanie Butland](https://ropensci.org/authors/stefanie-butland/) points you to resources.
* You prepare a blog post
    * either directly as a Markdown file 
    * or from R Markdown
  If you want to execute code, use the R Markdown post template. If not, use a Markdown post template. 
* You make a pull request to the website repo, review ensues. 

CREATE AN EXAMPLE PR ONCE THE TEMPLATE IS DECIDED.

First read [the content guidance](https://docs.ropensci.org/roblog/articles/content-guidelines.html) then the technical guidance. Use the navbar at the top of this website to navigate content. The [checklists](https://docs.ropensci.org/roblog/articles/checklists.html) will help you not forget bits and pieces.

## Installation

``` r
install.packages("roblog", repos = "https://dev.ropensci.org")
```
