---
title: "Checklists"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{checklists}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

In the first comment of your pull request submitting a post, please copy-paste the checklist corresponding to your post (hover, a copy-paste button will appear at the top-right corner of the shaded area) and check tasks.

## Post about a peer-reviewed package

```{r, echo = FALSE}
library("magrittr")
c(readLines(system.file("checklists", "submission-checklist.csv",
                  package="roblog")),
  readLines(system.file("checklists", "submission-checklist-peer-reviewed-pkg.csv",
                  package="roblog"))) %>% 
  gluedown::md_task() %>%
  glue::glue_collapse("\n") -> x

glue::glue("````markdown\n{x}\n````") %>% 
  knitr::asis_output()
```


## Any other post

```{r, echo = FALSE}
library("magrittr")
readLines(system.file("checklists", "submission-checklist.csv",
                  package="roblog"))%>%
  gluedown::md_task() %>%
  glue::glue_collapse("\n") -> x

glue::glue("````markdown\n{x}\n````") %>% 
  knitr::asis_output()
```
